### ISSUE TITLE
do not show description twice

### ISSUE THREAD

**Issue by r10s** [webxdc/appstore-bot#45]
the "app cards" can be shown shrinked as well as expanded - which is a pretty nice feature and looks great already!

however, when expected, the description is shown twice - this clutters UI and makes things harder to get. when reading a card, you will read the same information twice.

i suggest to hide the shortened variation in case the card is expected.

<img width=320 src=https://github.com/webxdc/appstore-bot/assets/9800740/2331565f-cd83-4b0d-a32a-0509e7b8da5c>

**Comment by Septias** [comment]
I actually think removing it is actually worse because it draws attention. The actual clutter is not a clutter as such because it is expected and known text. Someone will not give it too much attention because the use case is already known. At least thats what I think and is also the reason why I removed the initial fade transition.

**Comment by r10s** [comment]
hm, not convinced :) however, i would also not die on that hill, maybe also not the time for nitpicking. so, feel free to close unless you want to give it a try

**Comment by Septias** [comment]
I'll keep it in the back of my head
